openapi: 3.0.0
info:
  title: 'Clusters REST API'
  description: >-
    Create, Update Delete, Get and List Run:AI Clusters. <br> <br>
    To streamline resource allocation and  prioritize work, Run:AI introduces the concept of __Clusters__. Clusters are quota entities that associate a Cluster name with GPU allocation and allocation preferences. <br> <br>
    A Researcher submitting a Job needs to associate a Cluster name with the request. The Run:AI scheduler will compare the request against the current allocations and the Cluster and determine whether the workload can be allocated resources or whether it should remain in the queue for future allocation.
  version: '1.0'
servers:
  - url: 'https://app.run.ai/v1/k8s'
  - url: 'https://staging.run.ai/v1/k8s'
tags:
  - name: Login
  - name: Cluster
#    description: description of cluster
paths:
  '/auth/login':
    post: 
      tags:
        - Login
      summary: Login
      security: []
      description: Log in with User/Password to receive a "Bearer" token, which is used to authenticate other API calls.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string      
      responses:
        '200' : 
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  tenant_id:
                    type: integer
                  access_token:
                    type: string
                  token_type:
                    type: string
                  expires_in: 
                    type: integer  
              example:
                tenant_id: 1
                access_token : "<bearer>"
                token_type : "bearer"
                expires_in: 86400
  '/clusters':
    post:
      tags:
        - Cluster
      summary: Create a new Cluster.
      description: Retrieve a Cluster given a Cluster ID.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cluster'
      requestBody:
#        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cluster'  
            example:
              name: "cluster-a"
              description: group-a-cluster
    get:
      tags:
        - Cluster
      summary: List Clusters in Cluster.
      description: Get list of all Clusters for a given Cluster.
      responses:
        '200':
          description: A JSON array of Clusters 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cluster'
  '/clusters/{cluster_uuid}':
    get:
      tags:
        - Cluster
      summary: Returns a Cluster by Id.
      description: Retrieve a Cluster given a Cluster ID.
      parameters:
        - name: cluster_uuid
          in: path
          required: true
          description: Cluster Identifier.
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cluster'
    delete:
      tags:
        - Cluster
      summary: Delete a Cluster.
      description: Delete a Cluster by Cluster ID. 
      parameters:
        - name: cluster_uuid
          in: path
          required: true
          description: Cluster Identifier.
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: Cluster with id 389 is deleted
  /clusters/{cluster_uuid}/installfile:
    get:
      tags:
        - Cluster
      summary: Returns a Cluster Installation file by Id.
      description: Retrieve a Cluster given a Cluster ID.
      parameters:
        - name: cluster_uuid
          in: path
          required: true
          description: Cluster identifier.
          schema:
            type: string
            format: uuid
        - in: query
          name: cloud
          description: Cloud type identifier.
          schema:
            type: string
            enum: [gke, aws, aks, op, airgapped]
      responses:
        '200':
          description: OK
          content:
            text/plain:
             schema: 
               type: string
               format: binary
components:
  schemas:    
    Cluster:
      properties:
        name:
          type: string
          example: cluster-a
        tenantId:
          type: integer
          example: 1
        clusterUuid:
          type: string
          format: uuid
          example: fa9b7d1c-2f08-42b8-b608-7b7c1fb40ea1
        createdAt:
          type: string
        description:
          type: string
      required:
      - name
      - clusterUuid
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
